FROM postgres

USER postgres
WORKDIR /app

COPY /src/sql/create-schema.sql /docker-entrypoint-initdb.d/createTables.sql
COPY /src/sql/insert-test-data.sql /docker-entrypoint-initdb.d/insertData.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432


