FROM postgres

USER postgres
WORKDIR /app

COPY /src/sql/1_createTables.sql /docker-entrypoint-initdb.d/1_createTables.sql
# COPY /src/sql/2_insertData.sql /docker-entrypoint-initdb.d/2_insertData.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432
