FROM postgres:17

# Criar a base de dados com script inicial
USER postgres
WORKDIR /docker-entrypoint-initdb.d

COPY ./src/sql/createTables.sql ./createTables.sql
#COPY ./src/sql/insert-test-data.sql ./2_insert-test-data.sql

EXPOSE 5432
