FROM postgres:17

# Criar a base de dados com script inicial
USER postgres
WORKDIR /docker-entrypoint-initdb.d

COPY ./src/sql/1_createTables.sql ./createTables-Test.sql
# COPY ./src/sql/2_insertData.sql ./insert-test-data.sql

EXPOSE 5432
